volumes:
  postgres-data:

services:
  pg-knex-playground:
    image: postgres:14-alpine
    command: postgres -c max_wal_size=4GB -c work_mem=4GB
    environment:
      POSTGRES_DB: pg-knex-playground
      POSTGRES_USER: pg-knex-playground
      POSTGRES_PASSWORD: pg-knex-playground
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:6000:5432"
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U pg-knex-playground -d pg-knex-playground"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
