volumes:
  postgres-data:

services:
  node_service:
    image: example/node_service
    build: .
    command: "npm start"
    restart: unless-stopped
    depends_on:
      - pg_large_object

  pg_large_object:
    image: postgres:14-alpine
    command: postgres -c max_wal_size=4GB -c work_mem=4GB
    environment:
      POSTGRES_DB: pg-large-object
      POSTGRES_USER: pg-large-object
      POSTGRES_PASSWORD: pg-large-object
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg-large-object -d pg-large-object"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
